# Server
server.port=8000

spring.profiles.active=dev
spring.application.name=four-in-a-row
spring.jpa.open-in-view=false

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=WARN

# Swagger-UI API-Docs
# Deaktiviert das automatische Scannen der Controller (Generierung der JSON-Spec)
springdoc.api-docs.enabled=false
# Pfad zur YAML-Datei (muss in src/main/resources/static liegen)
springdoc.swagger-ui.url=/api-docs/4-in-a-row.yaml
# Pfad, unter dem das Swagger-UI im Browser aufgerufen wird
springdoc.swagger-ui.path=/swagger-ui.html