# Server
server.port=8000

spring.profiles.active=dev
spring.application.name=four-in-a-row
spring.jpa.open-in-view=false

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=WARN