# Server
server.port=8000

# Profiles
spring.profiles.include=local
spring.profiles.active=dev

# Generel
spring.application.name=four-in-a-row
spring.jpa.open-in-view=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jacksion.serialization.write-dates-as-timestamps: false

# TODO: wieder entfernen sobald Flyway aktiv verwendet wird
spring.flyway.enabled=false

# Logging
logging.level.root=INFO
logging.level.de.paulm.four_in_a_row=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security.web.csrf.CsrfFilter=WARN
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=WARN

logging.level.org.hibernate=WARN
logging.pattern.console=%d{HH:mm:ss.SSS} %-15([%thread]) %highlight(%-5level) %-35.35logger{35} - %kvp %msg%n

# Swagger-UI API-Docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.url=/api-docs/4-in-a-row.yaml
springdoc.swagger-ui.path=/swagger-ui.html