# Prod DB
spring.datasource.url=${FIAR_DB_URL}
spring.datasource.username=${FIAR_DB_USER}
spring.datasource.password=${FIAR_DB_PASS}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# H2 Console aus!
spring.h2.console.enabled=false

# Logging
logging.level.root=INFO

# REST
application.security.cookie-secure = true