# Server
server.port=8008

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fourinarow
spring.datasource.username=prod_user
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Sicherheit
spring.h2.console.enabled=false
